language: node_js
node_js:
  - "8"
env:
  - CXX=g++-4.8
services:
  - postgresql
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - yarn
before_script:
  - cp knexfile.travis.js knexfile.js
  - psql -c 'create database travis_ci_test;' -U postgres
  - yarn run migrate-test
script:
  - yarn run test-once
after_success:
  - npm run coveralls
