version: '3'

services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile-prod
    ports:
      - '2052:2052'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://mdnote-user:mdnote-mdnote@10.0.0.45/mdnote-prod
      - TOKEN_SECRET=aiufhaeufhsd
