FROM mhart/alpine-node:8.9.4

RUN mkdir -p /usr/src/app/src

WORKDIR /usr/src/app


ENV NODE_ENV $NODE_ENV
ENV DATABASE_URL $DATABASE_URL

ENV PATH /usr/src/app/node_modules/.bin:$PATH

ADD package.json /usr/src/app/package.json
ADD knexfile.js /usr/src/app/knexfile.js
ADD docker-entrypoint-prod.sh /usr/src/app/docker-entrypoint-prod.sh

RUN npm install
RUN npm install -g pm2


ADD . /usr/src/app
# RUN ls

# CMD ["npm", "run", "dev"]
CMD ["./docker-entrypoint-prod.sh"]
